dist: bionic
language: python
python: 3.7

install:
  - pip3 install -r requirements.txt

script: true

before_deploy:
  - mkdocs build --verbose --clean --strict

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_KEY
  keep_history: true
  local_dir: site
  target_branch: master
  repo: opensight-cv/opensight-cv.github.io
  on:
    branch: 
      - master
