site_name: OpenSight
theme:
  name: 'material'
  favicon: 'assets/favicon.ico'
  palette:
    primary: teal
    accent: indigo 
  logo:
    icon: 'remove_red_eye'
repo_name: opensight-cv/opensight
repo_url: https://github.com/opensight-cv/opensight
edit_uri: https://github.com/opensight-cv/docs/edit/master/docs

nav: 
  - Home: index.md
  - Getting Started:
    - (TODO) Hardware: getting-started/hardware.md
    - (TODO) Installation: getting-started/installation.md
    - (TODO) Upgrading: getting-started/upgrading.md
  - Modules:
    - (TODO) Contours: modules/contours.md 
    - (TODO) Video IO: modules/videoio.md 
    - (TODO) Color Operations: modules/color.md 
    - (TODO) Mask Operations: modules/mask.md 
    - (TODO) Drawing Operations: modules/draw.md 
    - (TODO) NetworkTables: modules/nt.md 
  - Advanced:
    - Creating Modules: creating-modules.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

copyright: 'Copyright &copy; 2019. MIT License'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/opensight-cv'
