site_name: OpenSight
theme:
  name: 'material'
  favicon: 'assets/favicon.ico'
  palette:
    primary: teal
    accent: teal
  logo:
    icon: 'remove_red_eye'
repo_name: opensight-cv/opensight
repo_url: https://github.com/opensight-cv/opensight
edit_uri: https://github.com/opensight-cv/docs/edit/master/docs

nav:
  - Home: index.md
  - Quick Start:
    - Hardware: quickstart/hardware.md
    - Installation: quickstart/installation.md
    - Upgrading: quickstart/upgrading.md
    - Getting Started: quickstart/getting-started.md
  - Modules:
    - Contours: modules/contours.md
    - Video IO: modules/videoio.md
    - Color Operations: modules/color.md
    - Mask Operations: modules/mask.md
    - Drawing Operations: modules/draw.md
    - NetworkTables: modules/nt.md
  - Module Development:
    - Introduction: module-dev/intro.md
    - Module Structure: module-dev/structure.md
    - Glossary: module-dev/glossary.md
  - Roadmap and Contributing: roadmap.md
  - Planned Pages: planned.md

markdown_extensions:
  - toc:
      permalink: true
  - admonition
  - footnotes
  - codehilite
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - def_list

copyright: 'Copyright &copy; 2019. MIT License'

extra:
  social:
    - type: 'github'
      link: 'https://github.com/opensight-cv'
